version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-net

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - app-net

  pizza-rest:
    image: garmoza/pizza-rest:0.0.2-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
      PIZZA_KAFKA_TOPIC_KITCHEN: 'super-kitchen'
    networks:
      - app-net

  pizza-kitchen:
    image: garmoza/pizza-kitchen:0.0.2-SNAPSHOT
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
      PIZZA_KAFKA_TOPIC_KITCHEN: 'super-kitchen'
    networks:
      - app-net

networks:
  app-net:
    name: pizza-net