server:
  port: 8081

spring:
  datasource:
    generate-unique-name: false
    name: pizza

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  kafka:
    bootstrap-servers: 'localhost:9092'

pizza:
  kafka-topic:
    kitchen: kitchen
    app: ready